Fixed indentation at the mac_install function

diff --git a/ServerGenesis b/ServerGenesis
--- a/ServerGenesis
+++ b/ServerGenesis
@@ -96,28 +96,28 @@ fi
 # Mac install
 mac_install()
 {
-	if [ -d /Applications ] && [ ! -d /usr/local/Cellar/docker ] || [ ! -d /opt/homebrew/Cellar/docker ]
-	then
-	    echo "You are running macOS!"
-	    echo "Homebrew is not installed, installing Mac-specific dependency..."
-	    sleep 2
-	    xcode-select --install
-	    NONINTERACTIVE=1 sudo /bin/bash -c \
-	    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-	    echo "Installing Docker for Mac..."
-	    brew install --cask docker
-	    open -a /Applications/Docker.app
-	    sleep 90
-	    # Help by Gemini 2.5 Pro to check for the running dockerd daemon
-	    local docker_daemon_check
-	    docker_daemon_check=$(docker ps > /dev/null 2>&1)
-	    if [[ ! $docker_daemon_check ]]
-	    then
-			echo "FATAL ERROR: You did not activate dockerd in the Docker Desktop settings!
-			Docker requires dockerd to function. The script is now going to exit."
-			exit 1
-	    fi
-	fi
+    if [ -d /Applications ] && [ ! -d /usr/local/Cellar/docker ] || [ ! -d /opt/homebrew/Cellar/docker ]
+    then
+        echo "You are running macOS!"
+        echo "Homebrew is not installed, installing Mac-specific dependency..."
+        sleep 2
+        xcode-select --install
+        NONINTERACTIVE=1 sudo /bin/bash -c \
+        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+        echo "Installing Docker for Mac..."
+        brew install --cask docker
+        open -a /Applications/Docker.app
+        sleep 90
+        # Help by Gemini 2.5 Pro to check for the running dockerd daemon
+        local docker_daemon_check
+        docker_daemon_check=$(docker ps > /dev/null 2>&1)
+        if [[ ! $docker_daemon_check ]]
+        then
+            echo "FATAL ERROR: You did not activate dockerd in the Docker Desktop settings!
+            Docker requires dockerd to function. The script is now going to exit."
+        exit 1
+        fi
+    fi
 }
 
 mac_install
